name: vercel-serverless-api-tests-Status

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:
    inputs:
      run:
        description: 'If you want to run the action'
        default: 'YES!'
        required: false

jobs:
  Check-Status:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm i vercel-serverless-tests
    - run: npm run vercel-serverless-api-tests-status
